[profile.default]
src = "src"
script = "script"
out = "out"
test = "test"
libs = ["node_modules", "lib"]
solc = "0.8.20"
auto_detect_solc = false
bytecode_hash = "none"
evm_version = "paris"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 130
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
bnbtestnet = "${BNB_TESTNET_RPC_URL}"

[etherscan]
bnbtestnet = {key = "${BNB_API_KEY}", url = "${BNB_TESTNET_RPC_URL}"}
